# .github/workflows/ci.yml
name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest        # Linux VM is fastest/cheapest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install project (editable) + test deps
        run: |
          python -m pip install -U pip
          python -m pip install -e . pytest pynput
      - name: Run unit tests
        run: python -m pytest -q